FROM jupyter/scipy-notebook@sha256:fca4bcc9cbd49d9a15e0e4df6c666adf17776c950da9fa94a4f0a045d5c4ad33

RUN pip install \
    adversarial-robustness-toolbox==1.19.1 \
    catboost==1.2.8 \
    eagerpy==0.30.0 \
    foolbox==3.3.4 \
    GPy==1.13.2 \
    kornia==0.8.1 \
    lief==0.16.5 \
    lightgbm==4.6.0 \
    numpy==1.24.3 \
    plotly==6.0.1 \
    requests==2.31.0 \
    torch==2.7.0 \
    torchaudio==2.7.0 \
    torchvision==0.22.0 \
    xgboost==3.0.0

RUN pip install kornia_rs==0.1.9